server:
  port: 8083
  address: 0.0.0.0
  servlet:
    context-path: /catalog

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  sql:
    init:
      schema-locations: classpath:database/jpetstore-hsqldb-schema.sql
      data-locations: classpath:database/jpetstore-hsqldb-dataload.sql
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      repositories:
        enabled: false
  session:
    redis:
      namespace: JPetStore6
      repository-type: indexed

mybatis:
  type-aliases-package: org.mybatis.jpetstore.*.domain
  mapper-locations: classpath:mapperXML/*.xml

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
grpc:
  server:
    port: 9093
