version: '3.8'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
#    # Linux에서 host.docker.internal 사용을 위해:
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
