version: '3.8'
services:
  discovery-server:
    image: minskim2/discovery-server:latest
    ports:
      - "8761:8761"
    extra_hosts:
      - "myhost:host-gateway"
    env_file:
      - ./common.env

  gateway-service:
    depends_on:
      - discovery-server
    image: minskim2/gateway-service:latest
    ports:
      - "8880:8880"
    extra_hosts:
      - "myhost:host-gateway"
    env_file:
      - ./common.env

  account-service:
    depends_on:
      - gateway-service
    image: minskim2/account-service:latest
    ports:
      - "8081:8081"
    extra_hosts:
      - "myhost:host-gateway"
    env_file:
      - ./common.env
      - ./account_service.env

  cart-service:
    depends_on:
      - gateway-service
    image: minskim2/cart-service:latest
    ports:
      - "8082:8082"
    extra_hosts:
      - "myhost:host-gateway"
    env_file:
      - ./common.env
      - ./cart_service.env

  catalog-service:
    depends_on:
      - gateway-service
    image: minskim2/catalog-service:latest
    ports:
      - "8083:8083"
    extra_hosts:
      - "myhost:host-gateway"
    env_file:
      - ./common.env
      - ./catalog_service.env

  order-service:
    depends_on:
      - gateway-service
    image: minskim2/order-service:latest
    ports:
      - "8084:8084"
    extra_hosts:
      - "myhost:host-gateway"
    env_file:
      - ./common.env
      - ./order_service.env