version: '3.8'
services:
  account-service:
    build:
      context: ../..
      dockerfile: ./AccountService/Dockerfile
    ports:
      - "8081:8081"
    extra_hosts:
      - "myhost:host-gateway"
    env_file:
      - ./common.env
      - ./account_service.env

  cart-service:
    build:
      context: ../..
      dockerfile: ./CartService/Dockerfile
    ports:
      - "8082:8082"
    extra_hosts:
      - "myhost:host-gateway"
    env_file:
      - ./common.env
      - ./cart_service.env

  catalog-service:
    build:
      context: ../..
      dockerfile: ./CatalogService/Dockerfile
    ports:
      - "8083:8083"
    extra_hosts:
      - "myhost:host-gateway"
    env_file:
      - ./common.env
      - ./catalog_service.env

  order-service:
    build:
      context: ../..
      dockerfile: ./OrderService/Dockerfile
    ports:
      - "8084:8084"
    extra_hosts:
      - "myhost:host-gateway"
    env_file:
      - ./common.env
      - ./order_service.env