server:
  port: 8084
  address: 0.0.0.0
#  servlet:
#    context-path: /order

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  sql:
    init:
      schema-locations: classpath:database/jpetstore-hsqldb-schema.sql
      data-locations: classpath:database/jpetstore-hsqldb-dataload.sql

mybatis:
  type-aliases-package: org.mybatis.jpetstore.domain
  mapper-locations: classpath:mapperXML/*.xml
