server:
  port: 8880
  address: 0.0.0.0
  forward-headers-strategy: native  # X-Forwarded-* 신뢰

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              lower-case-service-id: true
              enabled: true
          default-filters:
            - RemoveResponseHeader=Server
            - AddResponseHeader=X-Gateway, gateway-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}