server:
  port: 8880
  address: 0.0.0.0
  forward-headers-strategy: native  # X-Forwarded-* 신뢰

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false # 자동 라우팅 비활성화
          default-filters:
            - RemoveResponseHeader=Server
            - AddResponseHeader=X-Gateway, gateway-service
          routes:
            - id: account-service
              uri: lb://account-service
              predicates:
                - Path=/account/**
            - id: cart-service
              uri: lb://cart-service
              predicates:
                - Path=/cart/**
            - id: catalog-service
              uri: lb://catalog-service
              predicates:
                - Path=/catalog/**
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/order/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}